;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-newline-and-maybe-indent
	indent-for-tab-command
	markdown-outdent-or-delete
	rjsx-delete-creates-full-tag
	sgml-slash
	sp-remove-active-pair-overlay
	))

(setq mc/cmds-to-run-once
      '(
	switch-to-buffer
	))
